package com.hejinwei.diary.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hejinwei.diary.dao.mybatis.model.Comment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    Comment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Aug 10 17:28:26 CST 2016
     */
    int updateByPrimaryKey(Comment record);
    
    int selectCountByDiaryId(@Param("diaryId") Long diaryId);
    
    List<Comment> selectPageByDiaryId(@Param("diaryId") Long diaryId, 
    		@Param("startIndex") Integer startIndex, @Param("pageSize") Integer pageSize);
    
    void updateStatus(@Param("commentId") Long commentId, @Param("status") Byte status);
}