package com.hejinwei.diary.dao.mybatis.mapper;

import com.hejinwei.diary.dao.mybatis.model.DiaryPassword;

public interface DiaryPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    int deleteByPrimaryKey(Long diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    int insert(DiaryPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    int insertSelective(DiaryPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    DiaryPassword selectByPrimaryKey(Long diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    int updateByPrimaryKeySelective(DiaryPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_passwords
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    int updateByPrimaryKey(DiaryPassword record);
    
    void insertOrUpdate(DiaryPassword diaryPassword);
}