package com.hejinwei.diary.dao.mybatis.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hejinwei.diary.dao.mybatis.model.Diary;

public interface DiaryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int deleteByPrimaryKey(Long diaryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int insert(Diary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int insertSelective(Diary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	Diary selectByPrimaryKey(Long diaryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Diary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Diary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diaries
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	int updateByPrimaryKey(Diary record);

	
	int selectDiaryCount(@Param("userId") Long userId, @Param("type") Byte type);
	
	List<Diary> selectDiaryPage(@Param("userId") Long userId, @Param("type") Byte type, 
    		@Param("startIndex") Integer startIndex, @Param("pageSize") Integer pageSize);
	
	int selectDiaryCountForProfile(@Param("userId") Long userId, @Param("type") Byte type);
	
	List<Diary> selectDiaryPageForProfile(@Param("userId") Long userId, @Param("type") Byte type,
			@Param("startIndex") Integer startIndex, @Param("pageSize") Integer pageSize);
	
	void updateDeleteStatus(@Param("diaryId") Long diaryId, @Param("status") Byte status);

	Long selectUserIdByDiaryId(@Param("diaryId") Long diaryId);

}
