package com.hejinwei.diary.dao.mybatis.mapper;

import com.hejinwei.diary.dao.mybatis.model.Test;

public interface TestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	int insert(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	int insertSelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	Test selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	int updateByPrimaryKeySelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	int updateByPrimaryKey(Test record);
}