package com.hejinwei.diary.dao.mybatis.mapper;

import org.apache.ibatis.annotations.Param;

import com.hejinwei.diary.dao.mybatis.model.User;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	User selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	int updateByPrimaryKey(User record);

	User selectByName(@Param("name") String name);
	
	String selectSign(@Param("userId") Long userId);
}