package com.hejinwei.diary.dao.mybatis.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.diary_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long diaryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.to_user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long toUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.to_comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long toCommentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.content
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.to_nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private String toNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.status
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.add_time
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private Long addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comments.head_image
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	private String headImage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.comment_id
	 * @return  the value of comments.comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.comment_id
	 * @param commentId  the value for comments.comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.diary_id
	 * @return  the value of comments.diary_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getDiaryId() {
		return diaryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.diary_id
	 * @param diaryId  the value for comments.diary_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setDiaryId(Long diaryId) {
		this.diaryId = diaryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.user_id
	 * @return  the value of comments.user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.user_id
	 * @param userId  the value for comments.user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.to_user_id
	 * @return  the value of comments.to_user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getToUserId() {
		return toUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.to_user_id
	 * @param toUserId  the value for comments.to_user_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setToUserId(Long toUserId) {
		this.toUserId = toUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.to_comment_id
	 * @return  the value of comments.to_comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getToCommentId() {
		return toCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.to_comment_id
	 * @param toCommentId  the value for comments.to_comment_id
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setToCommentId(Long toCommentId) {
		this.toCommentId = toCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.content
	 * @return  the value of comments.content
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.content
	 * @param content  the value for comments.content
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.to_nickname
	 * @return  the value of comments.to_nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public String getToNickname() {
		return toNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.to_nickname
	 * @param toNickname  the value for comments.to_nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setToNickname(String toNickname) {
		this.toNickname = toNickname == null ? null : toNickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.nickname
	 * @return  the value of comments.nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.nickname
	 * @param nickname  the value for comments.nickname
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.status
	 * @return  the value of comments.status
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.status
	 * @param status  the value for comments.status
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.add_time
	 * @return  the value of comments.add_time
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public Long getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.add_time
	 * @param addTime  the value for comments.add_time
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comments.head_image
	 * @return  the value of comments.head_image
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public String getHeadImage() {
		return headImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comments.head_image
	 * @param headImage  the value for comments.head_image
	 * @mbggenerated  Thu Aug 11 16:42:06 CST 2016
	 */
	public void setHeadImage(String headImage) {
		this.headImage = headImage == null ? null : headImage.trim();
	}
	
	public String getAddDateStr() {
		if (addTime == null) {
			return "";
		}
		
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		try {
			return sdf.format(new Date(addTime));
		} catch (Exception e) {
			e.printStackTrace();
			return "";
		}
	}
}