package com.hejinwei.diary.dao.mybatis.model;

public class DiaryPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_passwords.diary_id
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    private Long diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_passwords.password
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_passwords.status
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_passwords.diary_id
     *
     * @return the value of diary_passwords.diary_id
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public Long getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_passwords.diary_id
     *
     * @param diaryId the value for diary_passwords.diary_id
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public void setDiaryId(Long diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_passwords.password
     *
     * @return the value of diary_passwords.password
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_passwords.password
     *
     * @param password the value for diary_passwords.password
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_passwords.status
     *
     * @return the value of diary_passwords.status
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_passwords.status
     *
     * @param status the value for diary_passwords.status
     *
     * @mbggenerated Fri Jul 29 11:39:02 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}