package com.hejinwei.diary.dao.mybatis.model;

public class Diary {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.diary_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private Long diaryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.user_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.title
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.date
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private Long date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.weather
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private String weather;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.private_type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private String privateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.status
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diaries.content
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.diary_id
	 * @return  the value of diaries.diary_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public Long getDiaryId() {
		return diaryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.diary_id
	 * @param diaryId  the value for diaries.diary_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setDiaryId(Long diaryId) {
		this.diaryId = diaryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.user_id
	 * @return  the value of diaries.user_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.user_id
	 * @param userId  the value for diaries.user_id
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.title
	 * @return  the value of diaries.title
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.title
	 * @param title  the value for diaries.title
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.date
	 * @return  the value of diaries.date
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public Long getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.date
	 * @param date  the value for diaries.date
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setDate(Long date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.type
	 * @return  the value of diaries.type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.type
	 * @param type  the value for diaries.type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.weather
	 * @return  the value of diaries.weather
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public String getWeather() {
		return weather;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.weather
	 * @param weather  the value for diaries.weather
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setWeather(String weather) {
		this.weather = weather == null ? null : weather.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.private_type
	 * @return  the value of diaries.private_type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public String getPrivateType() {
		return privateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.private_type
	 * @param privateType  the value for diaries.private_type
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setPrivateType(String privateType) {
		this.privateType = privateType == null ? null : privateType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.status
	 * @return  the value of diaries.status
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.status
	 * @param status  the value for diaries.status
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diaries.content
	 * @return  the value of diaries.content
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diaries.content
	 * @param content  the value for diaries.content
	 * @mbggenerated  Mon Jul 25 10:29:16 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}