package com.hejinwei.diary.dao.mybatis.model;

public class Test {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.name
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.age
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.height
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	private Integer height;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id
	 * @return  the value of test.id
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id
	 * @param id  the value for test.id
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.name
	 * @return  the value of test.name
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.name
	 * @param name  the value for test.name
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.age
	 * @return  the value of test.age
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.age
	 * @param age  the value for test.age
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.height
	 * @return  the value of test.height
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.height
	 * @param height  the value for test.height
	 * @mbggenerated  Thu Jul 21 10:20:26 CST 2016
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}
}