package com.hejinwei.diary.dao.mybatis.model;

import java.io.Serializable;

public class User implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6118395558237670747L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_id
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.nickname
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.head_image
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private String headImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sign
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	private String sign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_id
	 * @return  the value of users.user_id
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_id
	 * @param userId  the value for users.user_id
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.nickname
	 * @return  the value of users.nickname
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.nickname
	 * @param nickname  the value for users.nickname
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.head_image
	 * @return  the value of users.head_image
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public String getHeadImage() {
		return headImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.head_image
	 * @param headImage  the value for users.head_image
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setHeadImage(String headImage) {
		this.headImage = headImage == null ? null : headImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sign
	 * @return  the value of users.sign
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sign
	 * @param sign  the value for users.sign
	 * @mbggenerated  Mon Jul 25 09:57:21 CST 2016
	 */
	public void setSign(String sign) {
		this.sign = sign == null ? null : sign.trim();
	}
}